---
title: "iSSF"
author: "Amy Van Scoyoc"
date: "3/29/2022"
output: github_document
---

### Load Libraries
```{r}
library(here) #for setting working directory reproducibly
library(tidyverse) #for data manipulation
library(amt) #for animal movement tools (iSSF) 
library(sp) #for setting coordinate reference systems
library(lubridate) #for date/time adjustments
library(raster) #for environmental covariates
```


### Import environmental rasters
```{r}
r <- list.files(path=here("data_covariates"), pattern='tif$', full.names=TRUE)[c(1,3:4,6:7,9)]
envtrasters <- lapply(r, stack)
names(envtrasters) <- c("elev", "lc", "ndvi", "road", "slope", "water")
```


### Import coyote dataset
```{r}
#import 2021-2022 data
data <- read_csv(here("data", "coyote_2021.12.01_2022.03.04.csv")) %>% 
  drop_na(`Longitude[deg]`) %>% #remove any empty locations
  dplyr::select(x = `Longitude[deg]`, y = `Latitude[deg]`, #select & rename columns
                timestamp = `Acq. Time [UTC]`, ID = `Collar ID`) %>% 
  mutate(timestamp = lubridate::with_tz(ymd_hms(timestamp, tz="UTC"), tzone = "America/Los_Angeles")) %>% 
  nest(-ID) #group by collar ID

head(data)
```



```{r}
#make tracks for each animal id
d <- data %>% 
  mutate(trk = map(data, function(d){
    mk_track(d, x, y, timestamp, crs = CRS("+init=epsg:4326")) %>% #from WGS84
      transform_coords(CRS("+init=epsg:26910")) #transform to NAD83 UTM zone 10N
  }))

#check sampling rate is 1hr
d %>% 
  mutate(sr = lapply(trk, summarize_sampling_rate)) %>% 
  dplyr::select(ID, sr) %>% unnest
```


```{r}
#resample to 1hr
ssfdat <- d %>% 
  mutate(steps = map(trk, function(x){
    x %>% 
      track_resample(rate = hours(1), tolerance = minutes(5)) %>% #eliminate steps >1 hour
      filter_min_n_burst(min_n = 2)})) #eliminate bursts with <2 points

#compare
ssfdat %>%
  mutate(sr = lapply(steps, summarize_sampling_rate)) %>% 
  dplyr::select(ID, sr) %>% unnest
```

```{r}
lc <- raster(here("data_covariates", "HREC_landcover_reclass.tif"))
names(lc) <- "lc"

ssfdat <- ssfdat %>%
  mutate(moddata = map(steps, function(x){
    x %>% 
      steps_by_burst() %>% 
      # Randomly sample 10 steps per real step
      random_steps(n = 10) %>% 
      # Determine day or night from movement track data
      time_of_day(where = "start", include.crepuscule = TRUE) %>% 
      # Extract covariates from our raster stack
      amt::extract_covariates(lc,where="both")}))

```

```{r}
#scale covariates across all IDs
ssfdat.all <- do.call(rbind,ssfdat$moddata)
ID<-c()
for (i in 1:length(ssfdat[[1]])) {
   id <- rep(ssfdat[[i,1]],dim(ssfdat$moddata[[i]])[1])
   ID<-c(ID,id)
}
ssfdat.all$ID <- ID
ssfdat.all 

#create new step column
ssfdat.all$stepID <- ssfdat.all$ID*100000 + ssfdat.all$step_id_

```

```{r}
# Scale the covariates, turn "case" into a binary 1/0 variable, 
#   and add some movement parameters that we can use as covariates
ssfdat.all %>% mutate(lc_s_start = scale(lc_start), 
                  lc_s_end = scale(lc_end),
                  case_ = as.numeric(case_),
                  cos_ta = cos(ta_), 
                  log_sl = log(sl_)) -> ssfdat.all
```

```{r}
# Before we run our models, let's visualize our step lengths and turn angles

# Our turn angles are in radians
#   For ease of vizualization, we'll turn them into degrees
ssfdat.all %>%
  mutate(ta_degree = as_degree(ta_)) -> ssfdat.all

# First, we can look at the distribution of our turning angles as a rose plot
ssfdat.all %>% 
  filter(case_ == 1) %>% 
  ggplot(., aes(x = ta_degree, y=..density..)) + geom_histogram(breaks = seq(-180,180, by=20))+
  coord_polar(start = 0) + theme_minimal() + 
  scale_fill_brewer() + ylab("Density") + ggtitle("Angles Direct") + 
  scale_x_continuous("", limits = c(-180, 180), breaks = seq(-180, 180, by=20), 
                     labels = seq(-180, 180, by=20))

# Also check out the distribution of step lengths
ssfdat.all %>% 
  filter(case_ == 1) %>% 
  ggplot(., aes(x = sl_)) +  geom_histogram() + theme_minimal() + 
  scale_fill_brewer() + ylab("Count") + ggtitle("Step Lengths") 

# We can also look at how movement parameters might differ between day and night
# Here, we're looking at the log of step length
# Why do we take the log of the step length? Modify the plot code to see!
ssfdat.all %>% 
  filter(case_ == 1) %>% 
  ggplot(., aes(x = tod_start_, y = log(sl_))) + 
  geom_boxplot() + geom_smooth() 

# Let's also look at what used and available steps look like
# Here, the black point is our starting location and the colored points are our end locations
ssfdat.all %>% 
  filter(step_id_ == 2, ID == 35076) %>% 
  ggplot(.) + geom_point(aes(x = x2_,y = y2_,color = as.factor(case_))) + 
  geom_point(aes(x = x1_, y = y1_))
```

