---
title: "prep_covariates"
author: "Amy Van Scoyoc"
date: "3/30/2022"
output: github_document
---

### Import Libraries
```{r}
library(here) #for setting working directory reproducibly
library(tidyverse) #data tidying
library(sf) #modifying spatial attributes 
library(raster) #reclassify environmental covariates
```

### Reclassify Land Cover

```{r}
#import landcover layer
lc <- raster("/Users/Amy/Documents/Berkeley Classes/Brashares Lab/projects/coyote-movement/data_covariates/HREC_landcover_extended.tif")
#freq(lc)

#reclassify to developed (0), cultivated (1), and natural (2)
reclass_vec <- c(0, 20, NA, # water will be set to NA 
                20, 21, 1,  # we'll treat developed open space as cultivated (1s)
                21, 30, 0,  # developed and hardscape set to 0s
                30, 31, NA, # leave out barren
                31, 80, 2,  # natural habitats will have 2s 
                80, 89, 1,  # set cultivated space to 1s
                89, Inf, NA)# wetlands set to NA 

#create the matrix
reclass_m <- matrix(reclass_vec, ncol = 3, byrow = TRUE)

#reclassify land cover values 
lc_reclass <- reclassify(lc, reclass_m)
#freq(lc_reclass)
#plot(lc_reclass)

#write to file
writeRaster(lc_reclass, 
            filename = "/Users/Amy/Documents/Berkeley Classes/Brashares Lab/projects/coyote-movement/data_covariates/HREC_landcover_reclass.tif", 
            format = "GTiff",
            overwrite = T)
```


### Reclassify Roads

```{r}
#import roads layer
road <- raster(here("data_covariates", "HREC_roads_extended.tif"))

#reclassify to roads and NAs
reclass_vec <- c(-1, 50, NA, #non-road set to NA 
                50, Inf, 1) #all roads set to 1 

#create the matrix
reclass_m <- matrix(reclass_vec, ncol = 3, byrow = TRUE)

#reclassify road values 
rd_reclass <- reclassify(road, reclass_m)

#create distance surface (meters)
r_dist <- gridDistance(rd_reclass, origin = 1)
#plot(r_dist)

#write to file
writeRaster(r_dist, 
            filename = here("data_covariates",
                            "HREC_roads_reclass.tif"), 
            format = "GTiff",
            overwrite = T)
```

### Reclassify Water
```{r}
#import water layer
water <- raster(here("data_covariates", "HREC_water_extended.tif"))

#reclassify to water and NAs
reclass_vec <- c(-1, 0, NA, #non-water set to NA 
                0, Inf, 1) #all water set to 1 

#create the matrix
reclass_m <- matrix(reclass_vec, ncol = 3, byrow = TRUE)

#reclassify water values 
w_reclass <- reclassify(water, reclass_m)

#create distance surface (meters)
w_dist <- gridDistance(w_reclass, origin = 1)
#plot(w_dist)

#write to file
writeRaster(w_dist, 
            filename = here("data_covariates",
                            "HREC_water_reclass.tif"), 
            format = "GTiff",
            overwrite = T)
```


### Prep Dog Locations
```{r}
#import dog point layer
dog <- raster(here("data_covariates", "HREC_dog_locations.tif"))

#reclassify to dog and NAs
reclass_vec <- c(-1, 0, NA, #non-dog set to NA 
                0, Inf, 1) #all dog set to 1 

#create the matrix
reclass_m <- matrix(reclass_vec, ncol = 3, byrow = TRUE)

#reclassify values 
dog_reclass <- reclassify(dog, reclass_m)

#create distance surface (meters)
dog_dist <- gridDistance(dog_reclass, origin = 1)
#plot(dog_dist)

#write to file
writeRaster(dog_dist, 
            filename = here("data_covariates",
                            "HREC_dog_reclass.tif"), 
            format = "GTiff",
            overwrite = T)
```


### Prep Human Footprint Layer (2015) 
```{r}
#import dog point layer
hf <- raster(here("data_covariates", "HREC_humanfootprint_extended.tif"))

#create distance surface (meters)
hf_dist <- gridDistance(hf, origin = 255)
plot(hf_dist)

#write to file
writeRaster(hf_dist, 
            filename = here("data_covariates",
                            "HREC_hf_dist.tif"), 
            format = "GTiff",
            overwrite = T)
```