---
title: "prepData"
author: "Amy Van Scoyoc"
date: "4/13/2022"
output: github_document
---

```{r}
library(here) #reproducible working directory
library(tidyverse) #for data wrangling
library(lubridate) #for data/time
library(sp) #for UTM transformation
```

### Import and Combine Coyote field seasons
```{r}
#data table with coyote sex, id, collar start_date, collar end_date
datekey <- read_csv(here("data","coyote_datekey.csv")) 

#season 1 data (8-weeks)
season1 <- read_csv(here("data", "coyote_2020.11.08_2021.06.30.csv")) %>% 
  dplyr::select(x = `Longitude[deg]`, y = `Latitude[deg]`, 
                t = `Acq. Time [UTC]`, collar_id = `Collar ID`) %>%
  mutate(season = 1)

#season 2 data (16-weeks)
season2 <- read_csv(here("data", "coyote_2021.12.01_2022.03.04.csv")) %>% 
  dplyr::select(x = `Longitude[deg]`, y = `Latitude[deg]`, 
                t = `Acq. Time [UTC]`, collar_id = `Collar ID`) %>% 
  mutate(season = 2)

#combine field seasons
dat_all <- rbind(season1, season2) %>% 
  mutate(t = lubridate::with_tz(ymd_hms(t,tz="UTC"),"America/Los_Angeles")) %>% #adjust time
  drop_na(x) %>% #drop any missing locations
  left_join(., datekey, by = c("season", "collar_id")) %>% #join date table for filtering
  filter(t >= start_3d & t <= end) #filter 3-days after collaring
```
### Calculate GPS data metrics
```{r}
#calculate number of collared coyote dates (190 unique days)
dat_all %>% 
  mutate(julian_day = yday(t)) %>% 
  group_by(season) %>% 
  distinct(julian_day) #count unique julian day by season

#calculate mean days across individuals (mean 54 days)
dat_all %>% 
  group_by(ID) %>% 
  summarize(start = min(as.Date(t)), #first date per individual
            end = max(as.Date(t)), #last date per individual
            ndays = difftime(end, start, units = "days"), #n days per individual
            npoints = n()) %>% #number points
  summarize(n = mean(ndays)) #mean n days per individual
```

### Transform to UTMs
```{r}
#select and change column order
dat_all <- dat_all %>% dplyr::select(ID, x, y, t) %>% filter(ID != "M4") #remove coyote w 44pts
#transform to sp object
llcoord <- SpatialPoints(dat_all[,2:3],proj4string=CRS("+init=epsg:4326"))
#transform to utms
utmcoord <- spTransform(llcoord,CRS("+init=epsg:26910"))
# add UTM locations to data frame
dat_all$x <- attr(utmcoord,"coords")[,1]
dat_all$y <- attr(utmcoord,"coords")[,2]
```


### Export dataset to object for later use
```{r}
#arrange and convert to dataframe necessary for prepData
dat_all <- dat_all %>% arrange(ID, t) %>% data.frame() 
save(dat_all, file = "data_objects/dat_all.Rdata")
```